### ISSUE TITLE
Объедините объявление и присваивание значения

### ISSUE THREAD

**Issue by coursar** [aybatova/Tinkoff#2]
https://github.com/aybatova/Tinkoff/blob/fa3553beb102e4e2aad3b6dfacc0957e9f29fd9c/src/main/java/ru/itpark/CashbackService.java#L10-L13

Должно быть:
```java
int resultCommon = (sumCategorySimple + sumCategoryPriority * categoryPriorityPercent + sumCategorySuper * categorySuperPersent) / 100;
```

**Comment by aybatova** [comment]
done

**Comment by coursar** [comment]
@aybatova, хорошо указывать ссылку на коммит 09a42becbe24c2ac0f4d06c1d8950778c7c0c17e (нужно подставить полный хэш коммита)
