### ISSUE TITLE
Уберать лишний else и перевернуть условие

### ISSUE THREAD

**Issue by coursar** [aybatova/Tinkoff#3]
https://github.com/aybatova/Tinkoff/blob/fa3553beb102e4e2aad3b6dfacc0957e9f29fd9c/src/main/java/ru/itpark/CashbackService.java#L16-L21

1. Имеет смысл логически поменять условие, т.к. особый случай - это превышение лимита
1. В if'е итак стоит return, значит else можно убрать:
```java
if (resultCommon > resultLimit) { //  перевёрнутое условие
   return resultLimit; 
}

return resultCommon;
```

**Comment by aybatova** [comment]
done
